#!/usr/bin/env python3
"""
fx_families.py

Controlled vocabulary of “families” (clubs) for your FX vault.
– Keys are the family names (as you see them in Reaper).
– Values are their index numbers in your fxfolders.ini.

Edit the CONFIG block to add/remove or rename families.
"""

# ─── CONFIG: define your families here ────────────────────────────────────
FAMILIES = {
    "Emulation-Amp Cabs":            0,
    "Emulation-Amp Sims":            1,
    "Emulation-Pedals":              2,
    "STUDIO-Cocteau":           3,
    "STUDIOS":                  4,
    "TECH-Tape":                5,
    "TECH-Vinyl":               6,
    "Workhorses":               7,
    "ATMOS":                    8,
    "BRAND-Airwindows":         9,
    "BRAND-AMEK":               10,
    "BRAND-API":                11,
    "BRAND-Avalon":             12,
    "BRAND-Calrec":             13,
    "BRAND-EMI / Chandler":     14,
    "BRAND-Focusrite":          15,
    "BRAND-Harrison":           16,
    "BRAND-Helios":             17,
    "BRAND-Kush Audio":         18,
    "BRAND-Maag":               19,
    "BRAND-Manley":             20,
    "BRAND-MCI":                21,
    "BRAND-Neve":               22,
    "BRAND-Quad Eight":         23,
    "BRAND-Siemens":            24,
    "BRAND-SSL":                25,
    "BRAND-Studer":             26,
    "BRAND-Telefunken":         27,
    "BRAND-Trident":            28,
    "BRAND-ULTRA":              29,
    "BRAND-Weiss":              30,
    "DEV-Airwindows":           31,
    "DEV-chokehold jsfx":       32,
    "DEV-Demien D":             33,
    "DEV-FabFilter":            34,
    "DEV-Kilohearts":           35,
    "DEV-Melda":                36,
    "DEV-ReaClassical":         37,
    "DEV-SonicAxiom":           38,
    "DEV-Tukan":                39,
    "DEV-Voxengo":              40,
    "DEV-Weiss":                41,
    "Instruments-Containers":   42,
    "Instruments-Drums":             43,
    "Instruments-Foley":             44,
    "Instruments-Guitars":           45,
    "Instruments-Orchestral":        46,
    "Instruments-Pianos":            47,
    "Instruments-Synths Bass":       48,
    "Instruments-Synths Modern":     49,
    "Instruments-Synths Vintage":    50,
    "Instruments-Synths Vocal":      51,
    "Instruments-World":             52,
    "TOOLS--Composition":       53,
    "TOOLS--Notepad":           54,
    "TOOLS--Ozone":             55,
    "TOOLS--Spectrum Matching": 56,
    "COM--Bettermakers":        57,
    "COM--Bus Processors":      58,
    "COM-500 Racks":            59,
    "COM-Converters":                60,
    "COM-Bass / Low End":       61,
    "COM-Channel Management":      62,
    "COM-Chorus":               63,
    "Compression-1175/6":           64,
    "Compression-33609":            65,
    "Compression-Acqua":            66,
    "Compression-ADR":              67,
    "Compression-BUS":              68,
    "Compression-DBX":              69,
    "Compression-Distressor":       70,
    "Compression-Fairchild-EAR":    71,
    "Compression-Fatso":            72,
    "Compression-LA2A":             73,
    "Compression-Multi-Band":       74,
    "Compression-Nebula":           75,
    "Compression-RCA BA-6A":        76,
    "Compression-STA-Level":        77,
    "Compression-Summit":           78,
    "Compression-TNT":              79,
    "Compression-Tube Tech":        80,
    "Compression-Up / Expand":      81,
    "Compression-Vari-Mu":          82,
    "Compression-VCA":              83,
    "COMMON-De-Esser":               84,
    "COMMON-EQ Aqu-Neb":           85,
    "COMMON-EQ Pultec":            86,
    "COMMON-EQ Ultra":             87,
    "COMMON-High / Low Pass":      88,
    "COMMON-Limiter":              89,
    "COMMON-Mics":                 90,
    "COMMON-Pan":                  91,
    "COMMON-Preamp":               92,
    "Reverb Algorithmic":      93,
    "Reverb Digital":          94,
    "Reverb Multi":            95,
    "Reverb Plate":            96,
    "Reverb Convolution": 97,
    "Reverb Spaces":           98,
    "Reverb Spring":           99,
    "Reverb Tape":             100,
    "Saturation":           101,
    "Unmask / Res":         102,
    "Band Splitter":            103,
    "Clipper":                  104,
    "Colour/Character":         105,
    "Connectivity":             106,
    "Consoles":                 107,
    "Consoles: Airwindows":     108,
    "Consoles: CDSoundMaster":  109,
    "Consoles: Nebula":         110,
    "Creativity":               111,
    "Dither":                   112,
    "Envelope Shaper":          113,
    "Exciter":                  114,
    "Flanger":                  115,
    "Gainstaging/Metering":     116,
    "Harmonisers":              117,
    "Metronome":                118,
    "Mid/Side":                 119,
    "MIDI":                     120,
    "Monitoring":               121,
    "Multi-Effects":            122,
    "Noise":                    123,
    "Phase":                    124,
    "Reverse":                  125,
    "Rider":                    126,
    "Rotary":                   127,
    "Transient Design":         128,
    "Tubes & Transformers":     129,
    "Vibrato/Tremelo":          130,
    "Vocoder":                  131,
    "ZL Zero Latency Acqua":    132,
    "zz_Not Used":              133,
}
# ────────────────────────────────────────────────────────────────────────────

# Derived list of valid families
VALID_FAMILIES = list(FAMILIES.keys())

if __name__ == "__main__":
    print("🎚️  FX Families Controlled Vocabulary")
    print(f"Total families defined: {len(FAMILIES)}\n")
    for name, idx in FAMILIES.items():
        print(f"  {idx:03d} → {name}")